[package]
name = "nsql-echodb"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1.6.0"
imbl = "2.0.0"
nsql-storage-engine = { path = "../nsql-storage-engine" }
parking_lot = {version = "0.12.1", features = ["arc_lock", "send_guard"] }
thiserror = "1.0.40"
