[package]
name = "nsql-lmdb"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = { version = "0.11.0", default-features = false, features = ["lmdb"] }
nsql-storage-engine = { path = "../nsql-storage-engine" }

