[package]
name = "nsql-lmdb"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = { git = "https://github.com/meilisearch/heed", branch = "main", default-features = false }
nsql-storage-engine = { path = "../nsql-storage-engine" }

