[workspace]
members = [
    "nsql",
    "nsql-bind",
    "nsql-btree",
    "nsql-buffer",
    "nsql-catalog",
    "nsql-error",
    "nsql-ir",
    "nsql-pager",
    "nsql-parse",
    "nsql-serde",
    "nsql-fs",
    "nsql-test",
    "nsql-transaction",
    "nsql-util",
    "lruk",
]

[profile.bench]
debug = true
