CREATE TABLE integers (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    i int
);

INSERT INTO integers (i)
    VALUES (0),
    (1),
    (2),
    (NULL);

EXPLAIN ANALYZE TIMING OFF
SELECT
    id,
    i + 1
FROM
    integers
WHERE
    i <> 2;
