[package]
name = "nsql-plan"
version = "0.1.0"
edition = "2021"

[dependencies]
nsql-catalog = { path = "../nsql-catalog" }
nsql-core = { path = "../nsql-core" }
ir = { path = "../nsql-ir", package = "nsql-ir" }
