[package]
name = "nsql-transaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-util = { version = "0.1.0", path = "../nsql-util" }
thiserror = "1.0.40"
