[package]
name = "nsql-ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-catalog = { version = "0.1.0", path = "../nsql-catalog" }
rust_decimal = { version = "1.28.1", default-features = false }
