[package]
name = "nsql-execution"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.2"
async-trait = "0.1.64"
nsql-arena = { version = "0.1.0", path = "../nsql-arena" }
nsql-buffer = { version = "0.1.0", path = "../nsql-buffer" }
nsql-catalog = { version = "0.1.0", path = "../nsql-catalog" }
nsql-core = { version = "0.1.0", path = "../nsql-core" }
ir = { version = "0.1.0", path = "../nsql-ir", package = "nsql-ir" }
nsql-pager = { version = "0.1.0", path = "../nsql-pager" }
nsql-plan = { version = "0.1.0", path = "../nsql-plan" }
nsql-storage = { version = "0.1.0", path = "../nsql-storage" }
nsql-transaction = { version = "0.1.0", path = "../nsql-transaction" }
parking_lot = "0.12.1"
futures-util = "0.3.28"
tokio = { version = "1.27.0", default-features = false, features = ["sync"] }
dot-structures = "0.1.0"
smallvec = "1.10.0"
anyhow = "1.0.71"
