[package]
name = "lruk"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benches"
harness = false

[dependencies]
arrayvec = "0.7.2"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = "0.4.0"
proptest = "1.1.0"
