[package]
name = "nsql-pager"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
crc = "3.0"
parking_lot = { version = "0.12.1", default-features = false }

[dependencies.nsql-storage]
path = "../nsql-storage"

[dev-dependencies]
nsql-test = { path = "../nsql-test" }
proptest = "1.1.0"
test-strategy = "0.3.0"
