[package]
name = "nsql-pager"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.0"

nsql-serde = { path = "../nsql-serde" }
nsql-util = { path = "../nsql-util" }
parking_lot = "0.12.1"
pin-utils = "0.1.0"
tokio = { version = "1.25.0", default-features = false, features = [
    "io-util",
    "sync",
] }

[dependencies.nsql-fs]
path = "../nsql-fs"

[dev-dependencies]
nsql-test = { path = "../nsql-test" }
proptest = "1.1.0"
test-strategy = "0.3.0"
