[package]
name = "nsql-pager"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.0"

[dependencies.nsql-storage]
path = "../nsql-storage"

[dev-dependencies]
nsql-test = { path = "../nsql-test" }
