use expect_test::expect;

use crate::explain::check_explain;

#[test]
fn test_explain() -> nsql::Result<()> {
    check_explain(
        [
            "CREATE TABLE integers (id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, i int)",
            "INSERT INTO integers VALUES (0), (1), (2), (NULL)",
        ],
        "EXPLAIN ANALYZE TIMING OFF SELECT id, i + 1 FROM integers WHERE i <> 2",
        expect![[r#"
            projection (integers.id, #15(integers.i, 1))
              filter #6(integers.i, 2) in=4 out=4
                scan integers (id, i) in=0 out=5
        "#]],
    )?;

    Ok(())
}
