[package]
name = "nsql-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-serde = { version = "0.1.0", path = "../nsql-serde" }
smol_str = { version = "0.1.24", default-features = false }
