[package]
name = "nsql"
version = "0.1.0"
edition = "2021"

[dependencies]
error-stack = "0.3.1"
nsql-bind = { version = "0.1.0", path = "../nsql-bind" }
nsql-buffer = { path = "../nsql-buffer" }
nsql-catalog = { path = "../nsql-catalog" }
nsql-core = { version = "0.1.0", path = "../nsql-core" }
nsql-execution = { version = "0.1.0", path = "../nsql-execution" }
nsql-opt = { version = "0.1.0", path = "../nsql-opt" }

nsql-pager = { path = "../nsql-pager" }
nsql-parse = { version = "0.1.0", path = "../nsql-parse" }
nsql-plan = { version = "0.1.0", path = "../nsql-plan" }
nsql-storage = { path = "../nsql-storage" }
nsql-transaction = { path = "../nsql-transaction" }
thiserror = "1.0.38"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["time"] }
sqllogictest = "0.13.0"
async-trait = "0.1.64"
nsql-test = { path = "../nsql-test" }
walkdir = "2.3.2"
