[package]
name = "nsql-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
dashmap = "5.4.0"
nsql-core = { path = "../nsql-core" }
# nsql-storage = { path = "../nsql-storage" }
nsql-storage-engine = { path = "../nsql-storage-engine" }
nsql-util = { path = "../nsql-util" }
tracing = "0.1.37"
