[package]
name = "nsql-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
dashmap = "5.4.0"
nsql-core = { path = "../nsql-core" }
nsql-serde = { path = "../nsql-serde" }
nsql-storage = { path = "../nsql-storage" }
nsql-transaction = { path = "../nsql-transaction" }
nsql-util = { path = "../nsql-util" }
thiserror = "1.0.38"
tracing = "0.1.37"
