[package]
name = "nsql-catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-serde = { version = "0.1.0", path = "../nsql-serde" }
nsql-transaction = { version = "0.1.0", path = "../nsql-transaction" }
parking_lot = "0.12.1"
smol_str = "0.1.24"
