[package]
name = "nsql-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-catalog = { version = "0.1.0", path = "../nsql-catalog" }
nsql-pager = { version = "0.1.0", path = "../nsql-pager" }
nsql-serde = { version = "0.1.0", path = "../nsql-serde" }
nsql-transaction = { version = "0.1.0", path = "../nsql-transaction" }
