[package]
name = "nsql-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-arena = { version = "0.1.0", path = "../nsql-arena" }
nsql-buffer = { version = "0.1.0", path = "../nsql-buffer" }
nsql-core = { version = "0.1.0", path = "../nsql-core" }
nsql-pager = { path = "../nsql-pager" }
nsql-rkyv = { version = "0.1.0", path = "../nsql-rkyv" }
nsql-serde = { path = "../nsql-serde" }
nsql-transaction = { path = "../nsql-transaction" }
nsql-util = { version = "0.1.0", path = "../nsql-util" }
rkyv = { version = "0.7.40", default-features = false, features = ["archive_be", "size_32"] }
rust_decimal = { version = "1.28.1", default-features = false, features = ["rkyv"] }
thiserror = "1.0.38"

[dev-dependencies]
nsql-test = { path = "../nsql-test" }
proptest = "1.1.0"
test-strategy = "0.3.0"
