[package]
name = "nsql-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsql-catalog = { path = "../nsql-catalog" }
nsql-pager = { path = "../nsql-pager" }
nsql-serde = { path = "../nsql-serde" }
nsql-transaction = { path = "../nsql-transaction" }
thiserror = "1.0.38"
