[package]
name = "nsql-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
error-stack = "0.3.1"
libc = { version = "0.2.139", default-features = false }
tempfile = "3.3.0"
tokio-uring = { branch = "master", git = "https://github.com/tokio-rs/tokio-uring" }
