[package]
name = "nsql-bind"
version = "0.1.0"
edition = "2021"

[dependencies]
nsql-catalog = { version = "0.1.0", path = "../nsql-catalog" }
nsql-ir = { version = "0.1.0", path = "../nsql-ir" }
nsql-parse = { version = "0.1.0", path = "../nsql-parse" }
nsql-transaction = { version = "0.1.0", path = "../nsql-transaction" }
smol_str = "0.1.24"
thiserror = "1"
