on:
  push:
    branches:
      - master
name: CI
jobs:
  build_and_test:
    name: nsql test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        RUST_CHANNEL:
          - nightly

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup default ${{ env.RUST_CHANNEL }}
      - run: cargo test --release -- --ignored
