on: [push]
name: CI
jobs:
  build_and_test:
    name: nsql test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: cargo build --release --all-features
