on:
  push:
    branches:
      - master
name: CI
jobs:
  build_and_test:
    name: nsql test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: |
          rustup update --no-self-update nightly
          rustup default nightly
      - run: rustup run nightly cargo test --release -- --include-ignored
